server:
  port: 8081
  servlet:
    context-path: /demon-consumer-order
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    #开发环境
    active: dev
  application:
    name: demon-consumer-order
  cloud:
#    alibaba:
#      seata:
#        tx-service-group: demon
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/demon_order?useSSL=false
    username: root
    password: mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 10.189.32.69
    port: 8000
    lettuce:
      pool:
        max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000  # 连接超时时间（毫秒）


# swagger
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hu.pojo.po
  configuration:
    map-underscore-to-camel-case: true

#feign 连接超时时间
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000

#sql打印
logging:
  level:
    com:
      hu:
        mapper: debug
