server:
  port: 8081
  servlet:
    context-path: /demon-consumer-order
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: demon-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000

