server:
  port: 9527
  servlet:
    context-path: /demon-gateway
  tomcat:
    uri-encoding: utf-8

spring:
  # eureka 注册名称
  application:
    name: demon-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demon-payment-service #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          #uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://demon-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/demon-payment-service/payment/**          #断言，路径相匹配的进行路由

#logging:
#  level:
#    org.springframework.cloud.gateway: debug
