server:
  port: 9527
  servlet:
    context-path: /demon-gateway
  tomcat:
    uri-encoding: utf-8

spring:
  # eureka 注册名称
  application:
    name: demon-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demon-payment-service #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          #uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://demon-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/demon-payment-service/payment/**          #断言，路径相匹配的进行路由

eureka:
  instance:
    #eureka服务端的实例名称
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}@${server.port}
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://eureka7002.com:7002/eureka/  #互相注册
      defaultZone: http://127.0.0.1:7001/eureka/   #单机模式

#logging:
#  level:
#    org.springframework.cloud.gateway: debug
