server:
  port: 8086
  servlet:
    context-path: /demon-security-auth
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: demon-security-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/demon
    username: root
    password: mysql

management:
  endpoints:
    web:
      exposure:
        include: '*'

# OAuth2

security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:8086/demon-security-auth/auth/user
#code模式获取code/access_token
#http://localhost:8086/demon-security-auth/oauth/authorize?response_type=code&client_id=client&redirect_uri=http://127.0.0.1:8086/demon-security-auth/auth/user
#grant_type,client_id,code,redirect_uri,client_secret
#password模式获取access_token
#grant_type,client_id,username,password,client_secret

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hu.pojo.po
  configuration:
    map-underscore-to-camel-case: true