server:
  port: 9001
  servlet:
    context-path: /demon-nacos-provider
  tomcat:
    uri-encoding: utf-8

spring:
  # eureka 注册名称
  application:
    name: demon-nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'




