server:
  port: 8401
  servlet:
    context-path: /demon-sentinel
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: demon-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        # sentinel dashboard 启动地址
        dashboard: 127.0.0.1:8080
        # 默认为8719
        port: 8719
      # 流控规则持久化到nacos
      #      [
      #      {
      #        "resource":"/testA",
      #        "limitiApp":"default",
      #        "grade":1,
      #        "count":1,
      #        "strategy":0,
      #        "controlBehavior":0,
      #        "clusterMode":false
      #      }
      #      ]
      #      resource:资源名称，controller路径，无须spring.application.name
      #      limitiApp：来源应用
      #      grade：阈值类型：0表示线程数，1表示ops（请求个数）
      #      count：单机阈值
      #      strategy：流控模式：0表示直接，1表示关联，2表示链路
      #      controlBehavior：流控效果：0表示快速失败，1表示warm up，2表示排队等待
      #      clusterMode：是否集群
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

# 激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
